### ISSUE TITLE
ProGuard issue

### ISSUE THREAD

**Issue by ildar** [mjdenham/and-bible#96] opened 2017-06-17 02:35 UTC
Would you please look at this?
https://forum.f-droid.org/t/proguard-issues-in-f-droid/594/4

**Comment by mjdenham** [comment] 2017-06-20 21:09
Don't worry Ildar.  I have checked in the proguard config file.

**Comment by ildar** [comment] 2017-06-21 04:41
Martin, sorry, I think you are wrong.
[Build log](http://krt.marmaro.de/~krt/pub/share.JfEgTbrB5M.log) with the
issue (5 days old):
> Note: there were 6 references to unknown classes.
>       You should check your configuration for typos.
>       (
http://proguard.sourceforge.net/manual/troubleshooting.html#unknownclass)
> Note: there were 32 unkept descriptor classes in kept class members.
>       You should consider explicitly keeping the mentioned classes
>       (using '-keep').
>       (
http://proguard.sourceforge.net/manual/troubleshooting.html#descriptorclass)
> Note: there were 5 unresolved dynamic references to classes or interfaces.
>       You should check if you need to specify additional program jars.
>       (
http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclass)
> Note: there were 1 accesses to class members by means of introspection.
>       You should consider explicitly keeping the mentioned class members
>       (using '-keep' or '-keepclassmembers').
>       (
http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclassmember
)
> Warning: there were 36 unresolved references to classes or interfaces.
>          You may need to add missing library jars or update their
versions.
>          If your code works fine without the missing classes, you can
suppress
>          the warnings with '-dontwarn' options.
>          (
http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
> Warning: Exception while processing task java.io.IOException: Please
correct the above warnings first.
> :app:transformClassesAndResourcesWithProguardForRelease FAILED

But git log says you didn't change ProGuard config since May 8.
Can you recheck please?

**Comment by mjdenham** [comment] 2017-06-21 05:37
Why did you raise this issue? Is something broken?

**Comment by ildar** [comment] 2017-06-21 06:08
yep.
F-Droid is unable to build latest versions for a few month already. Krt
made the log, we discussed in the forum.
I'd like you to check the log and we together fix the problem. Though
that's by no means urgent as F-Droid current version is quite good.
FYI build status is here:
https://f-droid.org/wiki/page/net.bible.android.activity

**Comment by mjdenham** [comment] 2017-06-21 21:12
I suspect it is just an anomaly related to their checks.  Have you got a way of reproducing the error message?  We need to be able to reproduce the issue in order to fix it.

**Comment by ildar** [comment] 2017-06-22 05:18
I see.
Can you just confirm that gradle build works for you? Then we can get back
to the issue later, when F-Droid settle down (they are in the middle of
massive change now).
Thanks.

**Comment by mjdenham** [comment] 2017-06-22 16:27
Yes, I did a release just last week.

**Comment by ildar** [comment] 2017-08-29 10:10
Martin, f-droid guys helped me (us) with this issue:
(2017-08-29 15:33:52) mimi89999:
https://github.com/mjdenham/and-bible/commit/f5461b18d0f9c2bac10f94bf76f67ded8fbaa178
(2017-08-29 15:34:33) mimi89999: We are still on
JSword@fa6a44d05982a67f0122ffdd7b522d8ebcf43824
would you please look at it? Thanks!

**Comment by mjdenham** [comment] 2017-08-29 16:29
Could you send the links again.  I don't understand the reason for the first link and the second is broken.

**Comment by ildar** [comment] 2017-08-29 16:46
That was a pure IRC log fragment.
1st link is your commit we are actively commenting with you today :)
The second isn't a link, just the hash of the JSword commit.
I edited a bit my post, take a look.

**Comment by mjdenham** [comment] 2017-08-30 15:23
Maybe I am being slow, but I still can't glean any information from your comment.  Could you expand on it?

**Comment by ildar** [comment] 2017-08-31 11:35
That was the wild guess and appeared to be wrong. Still getting more info,
hang on.

**Closed** 2018-06-12 05:27 UTC
