### ISSUE TITLE
"Share current verse" excludes some words from the text

### ISSUE THREAD

**Issue by JohnAustinDev** [mjdenham/and-bible#46] opened 2015-11-16 08:55 UTC
When using "share current verse," all words in the verse text which are linked to a glossary are removed from the shared verse text.

This happens with any text having glossary links to an accompanying glossary, such as the UZVL module in IBT's repository, and most other IBT modules.

**Comment by mjdenham** [comment] 2015-11-21 15:29
Hi, 

Would you be able to send me the OSIS for one of the affected verses?

Martin

**Comment by JohnAustinDev** [comment] 2015-11-23 04:59
Martin,
Sure, here is OSIS from an effected UZVL verse (the word "muqaddas" is 
excluded from "Share current verse" text):

<verse sID="Gen.2.3" osisID="Gen.2.3"/>Xudo yettinchi kuni barcha 
yaratish ishlaridan dam olgani uchun, bu kunni muborak qilib, <reference 
type="x-glossary" osisRef="UZDOTL:MUQADDAS 
UZDNTL:MUQADDAS">muqaddas</reference>, deb boshqa kunlardan 
ajratdi.</p><verse eID="Gen.2.3"/>

But all text nodes in a verse should be preserved, unless their parent 
element has been specifically targeted for removal for a good reason 
(such as note elements, which may not be desired in "Share current 
verse" context). The default should be to keep all text nodes, unless 
you are removing their parent element for a specific purpose. Because, 
for example, someone else may use <seg> OSIS tags somewhere and then 
would its text nodes also be filtered out? (because they shouldn't be).
-John

**Comment by mjdenham** [comment] 2015-11-27 21:14
I have found 2 separate occurrences of this problem in different parts of the code.  One is caused by JSword and the other And Bible.  

The first occurrence, which you have found above, is a flaw in And Bible's OsisToCanonicalTextSaxHandler.

The second problem has the same symptoms as the first but is a flaw in JSword's code.  You can see the issue by selecting 'Compare translations' in And Bible.  This feature uses JSword's OSISUtil.getCanonicalText:
<pre>
plainText = OSISUtil.getCanonicalText(data.getOsisFragment());
</pre>

I plan to fix this but would first like to raise the question on JSword to make sure I get it as correct as possible.  We might also get a fix to JSword's OSISUtil.  Please join in when I raise the question on JSword.

**Comment by mjdenham** [comment] 2015-12-02 23:09
I have implemented a fix for this.  It is available on the Play Store alpha channel and in my Drive folder.  For simplicity I fixed the And Bible canonical text code and now use that everywhere which may have a slight performance impact.

**Comment by mjdenham** [comment] 2015-12-05 20:49
Tested and released.

**Closed by mjdenham** 2015-12-05 20:49 UTC
